const ADD_EMAIL = 'ADD_EMAIL';
const REQUEST_SUCCESSFUL = 'REQUEST_SUCCESSFUL';
const ADD_EXPENSE = 'ADD_EXPENSE';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const EDIT_EXPENSE = 'EDIT_EXPENSE';
const SAVE_EDIT_EXPENSE = 'SAVE_EDIT_EXPENSE';

export { ADD_EMAIL,
  REQUEST_SUCCESSFUL, ADD_EXPENSE, DELETE_EXPENSE, EDIT_EXPENSE, SAVE_EDIT_EXPENSE };
